apiVersion: apps/v1
kind: Deployment
metadata:
  name: studentsurvey
  namespace: hw2
  labels:
    app: studentsurvey
spec:
  replicas: 3
  selector:
    matchLabels:
      app: studentsurvey
  template:
    metadata:
      labels:
        app: studentsurvey
    spec:
      containers:
      - name: studentsurvey
        image: us-central1-docker.pkg.dev/vigilant-list-476000-n7/student-survey-repo/studentsurvey:1.0
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
