apiVersion: apps/v1
kind: Deployment
metadata:
  name: studentsurvey-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: studentsurvey
  template:
    metadata:
      labels:
        app: studentsurvey
    spec:
      containers:
      - name: studentsurvey
        image: us-central1-docker.pkg.dev/vigilant-list-476000-n7/studentsurvey-repo/studentsurvey:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 250m
            memory: 512Mi
