apiVersion: v1
kind: Service
metadata:
  name: studentsurvey-service
  labels:
    app: studentsurvey
spec:
  type: LoadBalancer
  selector:
    app: studentsurvey
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
