apiVersion: v1
kind: Service
metadata:
  name: studentsurvey-service
  annotations:
    cloud.google.com/backend-config: '{"default": "studentsurvey-backendconfig"}'
spec:
  type: LoadBalancer
  selector:
    app: studentsurvey
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
